name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: dependecies
      run: sudo apt install libgpac-dev libjpeg-dev zlib1g-dev libpng-dev
      
    - name: make
      run: make
